name: bebes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  shared_preferences: any
  flat_icons_flutter: ^1.0.2
  sqflite: any
  path_provider: any
  path: any
  uuid: any
  flutter_swipe_detector: any
  flutter_login: any
  http: any
  envify: any
  http_interceptor: any
  dio: any
  dio_cookie_manager: any
  cookie_jar: any
  connectivity_plus: any
  graphql_flutter: any
  emoji_picker_flutter: any
  flutter_keyboard_visibility: any

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  envify_generator: any
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
